### ISSUE TITLE
update tokio dependency 

### ISSUE THREAD

**Issue by lockbox** [DoumanAsh/async-timer#18]
need to update the tokio version to avoid some of the issues here.

https://deps.rs/crate/async-timer/0.7.4#vulnerabilities

**Comment by DoumanAsh** [comment]
Just a note for reference:
This doesn't affect async-timer iself

**Comment by lockbox** [comment]
Yeah I know, the pinned Tokio version is also a couple years old at this point (and doesnt break the tests)
