### ISSUE TITLE
The behavior of Interval

### ISSUE THREAD

**Issue by VirxEC** [DoumanAsh/async-timer#20]
It seems like the default behavior of `Interval` in this crate (which _is_ more precise than Tokio's default) is to not account for the time between `.await` calls. This results in Tokio's `Interval` being more precise _on average_ with it achieving 8.329971ms which is very close to 8.333ms despite the average deviation tick to tick being higher (this crate got 8.737788ms).

Is it possible for there to at least be an option to account for the time between `.await` calls?

Tested with `1.0.0-beta.12` and `0.7.4`

**Comment by DoumanAsh** [comment]
They way it works is that it gets restarted on successful Ready poll
https://github.com/DoumanAsh/async-timer/blob/master/src/interval.rs#L81
So it will be waiting for new notification from OS

AFAIK tokio timers are basically implemented on top of epoll/kqueue so they actually should be on par with this crate.

Still it is weird to me that timerfd/kqueue timers are so much worse than tokio's interval

Just for information on which system you run your tests?

**Comment by VirxEC** [comment]
Ubuntu 23.10 both with and without the tokio1 feature

**Comment by DoumanAsh** [comment]
Just a note without tokio1 feature it uses posix timers which are not as good in general
So only test with `tokio1` feature as it enables more efficient timerfd

in any case I understand problem somewhat, but it will be difficult to determine how to optimize overhead more

**Comment by DoumanAsh** [comment]
@VirxEC can you give a try to this branch?
https://github.com/DoumanAsh/async-timer/tree/interval_time_elapsed_adjustments

This is very basic adjustments to just schedule next call according to schedule (skipping every missed one)

**Comment by VirxEC** [comment]
I don't think skipping is the right call, now the interval is way off on average - way under instead of a little over with a average time between ticks of `6.316358ms`

**Comment by DoumanAsh** [comment]
I did some adjustments on the branch to offset overhead, but it might be better to re-work code to use native intervals instead to let OS guarantee consistent timing
Although it would mean multiple wake ups if task gets delayed for too long

**Comment by VirxEC** [comment]
I can confirm the new changes work as expected, I can't comment on OS native intervals.

**Comment by DoumanAsh** [comment]
I will release new version `1.0.0-beta.13` now with this change included
But from my experiments it seems tokio's timers will provide more consistent behavior (as it relies on underlying poll function) while this crate depends entirely on OS timer implementation, and it is only reliable on Linux 😢
